Traceback (most recent call last):
  File "main.py", line 339, in <module>
    if unknowns:
NameError: name 'unknowns' is not defined
