INFO:root:gpu device = cuda:0
INFO:root:epoch 0 lr 4.442566e-02
INFO:root:Epoch [1/20]
  0%|          | 0/3631 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 402, in <module>
    save_model_str=get('run_dir'))
  File "main.py", line 341, in create_run_ensemble_self
    train_score, train_loss, models_avg = ensemble_model.train_fn(optimizer, criterion, train_loader, device)
  File "/home/rkohli/aml-project/src/model.py", line 332, in train_fn
    logits = i_model(input)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rkohli/aml-project/src/model.py", line 250, in forward
    s0 = s1 = self.stem(input)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 343, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 340, in conv2d_forward
    self.padding, self.dilation, self.groups)
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not builtin_function_or_method
